name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check for updates
      id: check-updates
      run: |
        npx npm-check-updates --format json > updates.json || true
        if [ -s updates.json ]; then
          echo "updates-available=true" >> $GITHUB_OUTPUT
          echo "Updates available:"
          cat updates.json
        else
          echo "updates-available=false" >> $GITHUB_OUTPUT
          echo "No updates available"
        fi
        
    - name: Update patch versions
      if: steps.check-updates.outputs.updates-available == 'true'
      run: |
        # Update patch versions only for safety
        npx npm-check-updates --target patch --upgrade
        npm install
        
    - name: Run tests after update
      if: steps.check-updates.outputs.updates-available == 'true'
      run: |
        npm test -- --watchAll=false
        npm run lint
        
    - name: Create Pull Request
      if: steps.check-updates.outputs.updates-available == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update patch dependencies'
        title: '🔄 Automated Dependency Updates'
        body: |
          ## 📦 Automated Dependency Updates
          
          This PR contains automated updates to patch versions of dependencies.
          
          ### Changes:
          - Updated patch versions for security and bug fixes
          - All tests passed after updates
          - Linting checks passed
          
          ### Verification:
          - [ ] Review the changes
          - [ ] Test the app manually if needed
          - [ ] Merge if everything looks good
          
          **Note**: Only patch updates are applied automatically for safety.
          Major and minor updates require manual review.
          
          ---
          *This PR was created automatically by GitHub Actions*
        branch: automated/dependency-updates
        delete-branch: true
        
    - name: Check for major updates
      run: |
        echo "Checking for major/minor updates that need manual review..."
        npx npm-check-updates --target major > major-updates.txt || true
        if [ -s major-updates.txt ]; then
          echo "Major/minor updates available (require manual review):"
          cat major-updates.txt
          
          # Create an issue for manual review
          gh issue create \
            --title "📋 Manual Dependency Review Needed" \
            --body "$(echo -e "## Major/Minor Dependency Updates Available\n\nThe following updates require manual review:\n\n\`\`\`\n$(cat major-updates.txt)\n\`\`\`\n\n### Action Required:\n- Review each update for breaking changes\n- Test thoroughly before updating\n- Consider updating in separate PRs\n\n---\n*This issue was created automatically*")" \
            --label "dependencies,manual-review"
        else
          echo "No major/minor updates available"
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true